[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
