// SPDX-License-Identifier: CC0-1.0
pragma solidity >=0.7.0;

import "./ILockingContract.sol";
import "./IDecryptionContractWithKeyGeneration.sol";
import "./IDecryptionContractInceptionCallback.sol";

/**
 * @title ERC-7573 Locking Contract with asynchronous key generation.
 * @dev Optional same-chain extension for a locking contract whose key material
 * is generated by an IDecryptionContractWithKeyGeneration after asset inception.
 */
interface ILockingContractWithKeyGeneration is
    ILockingContract,
    IDecryptionContractInceptionCallback
{
    /**
     * @dev Emitted when the buyer authorizes a decryption contract as the key
     * source for a transfer whose key material is not available yet.
     * @param id Lifetime-unique identifier of this transfer leg.
     * @param amount The number of tokens to be transferred.
     * @param from The address of the seller.
     * @param to The address of the buyer.
     * @param transaction Immutable application-specific transfer data.
     * @param decryptionContract The authorized generated-key source.
     */
    event TransferInceptedWithKeyGeneration(
        uint256 id,
        int amount,
        address from,
        address to,
        bytes transaction,
        IDecryptionContractWithKeyGeneration decryptionContract
    );

    /**
     * @notice Initiates a transfer with asynchronously generated keys.
     * @dev The `from` and `to` participants MUST be supplied explicitly. `msg.sender`
     * identifies only the caller and MUST NOT, by itself, determine either participant.
     * Implementations MAY require `msg.sender` to be a participant or an authorized operator.
     * The locking contract MUST store the exact context and
     * decryptionContract. It MUST accept key material only from an inception whose
     * id and transaction match, whose payment sender is this asset buyer (to), whose
     * payment receiver is this asset seller (from), and whose callback is this
     * locking contract.
     * @param id Lifetime-unique identifier of this transfer leg.
     * @param amount The number of tokens to be transferred.
     * @param from The address of the seller.
     * @param to The address of the buyer.
     * @param transaction Immutable application-specific transfer data.
     * @param decryptionContract The authorized generated-key source.
     */
    function inceptTransfer(
        uint256 id,
        int amount,
        address from,
        address to,
        bytes memory transaction,
        IDecryptionContractWithKeyGeneration decryptionContract
    ) external;

    /**
     * @notice Completes the asset lock from immutable key material stored by the
     * authorized decryption contract.
     * @dev This function MAY be called by anyone: the caller conveys no authority.
     * The implementation MUST authenticate the stored decryption contract and match
     * the id, reversed participants, transaction and exact callback address. The
     * asset and payment amounts are independent and need not match. It MUST
     * require explicit key availability, and make this transition one-shot and
     * idempotent.
     * A direct onInceptionCompleted callback SHOULD invoke the same internal logic.
     * @param id Lifetime-unique identifier of this transfer leg.
     */
    function completeLock(uint256 id) external;

    /**
     * @notice Cancels an asynchronous asset inception before it has been locked.
     * @dev The buyer MUST be loaded from the stored inception rather than inferred from
     * `msg.sender`. Implementations MAY require `msg.sender` to be the buyer or an
     * authorized operator.
     * The implementation MUST retain the immutable context as a cancellation
     * tombstone and acknowledge a later matching authenticated completion without
     * locking, so asynchronous completion does not deadlock the failure-key path.
     * @param id Lifetime-unique identifier of this transfer leg.
     */
    function cancelTransfer(uint256 id) external;
}
