"""Translate vectors/onchain/*.json into contracts/test/Vectors.t.sol so the
same cases run on a real EVM with Foundry (`forge test`).

The registry is placed at the vector's registry address and the chain id is
set to the vector's chainId, so the preregistrationId check in ID.json
matches byte for byte.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
import sys  # noqa: E402
sys.path.insert(0, str(ROOT / "model"))
from ethcrypto import to_checksum  # noqa: E402

VEC = ROOT / "vectors" / "onchain"
OUT = ROOT / "contracts" / "test" / "Vectors.t.sol"

meta = json.loads((VEC / "_meta.json").read_text())


def ident(s):
    return re.sub(r"[^A-Za-z0-9_]", "_", s)


def b32(v):
    return f"bytes32({v})" if int(v, 16) else "bytes32(0)"


def who(name):
    return "address(0)" if name == "zero" else name


def arg(v, binds):
    if isinstance(v, str) and v.startswith("$"):
        return v[1:]
    return b32(v)


def gen_case(c):
    binds = sorted({s["expect"]["bind"] for s in c["steps"]
                    if "bind" in s.get("expect", {})})
    lines = [f"    /// {c['invariant']} ({c['level']}): {c['description']}",
             f"    function test_{ident(c['invariant'])}_{ident(c['name'])}() public {{"]
    lines += [f"        bytes32 {b};" for b in binds]
    for s in c["steps"]:
        a, exp = s["args"], s["expect"]
        if s["call"] == "getAttestation":
            lines += [
                "        {",
                f"            (,,, IPreregisteredCriteria.Verdict v,,) = reg.getAttestation({arg(a['preregistrationId'], binds)});",
                f"            assertEq(uint8(v), uint8(IPreregisteredCriteria.Verdict.{exp['verdict']}));",
                "        }"]
            continue
        lines.append(f"        vm.warp({s['timestamp']});")
        lines.append(f"        vm.prank({who(s['from'])});")
        if "revert" in exp:
            lines.append(f"        vm.expectRevert(); // {exp['revert']}")
        if s["call"] == "preregister":
            call = (f"reg.preregister({b32(a['criteriaDigest'])}, {b32(a['taskRef'])}, "
                    f"{a['obligationCount']}, hex\"{a['obligationFlags'][2:]}\", {a['expiry']}, "
                    f"{who(a['verifier'])}, {arg(a['supersedes'], binds)})")
            if "bind" in exp:
                lines.append(f"        {exp['bind']} = {call};")
            else:
                lines.append(f"        {call};")
            if exp.get("checkId"):
                lines.append(f"        assertEq({exp['bind']}, {b32(exp['preregistrationId'])});")
                lines.append(
                    f"        assertEq({exp['bind']}, keccak256(abi.encode(block.chainid, address(reg), "
                    f"{who(s['from'])}, {b32(a['criteriaDigest'])}, {b32(a['taskRef'])})));")
        elif s["call"] == "attestOutcome":
            lines.append(
                f"        reg.attestOutcome({arg(a['preregistrationId'], binds)}, {b32(a['bundleDigest'])}, "
                f"{b32(a['attestationDigest'])}, IPreregisteredCriteria.Verdict.{a['verdict']}, "
                f"hex\"{a['obligationOutcomes'][2:]}\");")
        elif s["call"] == "resolveExpired":
            lines.append(f"        reg.resolveExpired({arg(a['preregistrationId'], binds)});")
    lines.append("    }")
    return "\n".join(lines)


def main():
    cases = []
    for f in sorted(VEC.glob("*.json")):
        if not f.name.startswith("_"):
            cases += json.loads(f.read_text())
    actors = "\n".join(
        f'    address internal {n} = vm.addr(uint256(keccak256("erc8412:{n}")));'
        for n in meta["actors"])
    body = "\n\n".join(gen_case(c) for c in cases)
    OUT.write_text(f"""// SPDX-License-Identifier: CC0-1.0
// GENERATED by tools/gen_foundry_tests.py from vectors/onchain — do not edit by hand.
pragma solidity ^0.8.24;

import {{Test}} from "forge-std/Test.sol";
import {{PreregisteredCriteria, IPreregisteredCriteria}} from "../PreregisteredCriteria.sol";

contract ERC8412VectorsTest is Test {{
    PreregisteredCriteria internal reg;
{actors}

    function setUp() public {{
        vm.chainId({meta['chainId']});
        address at = {to_checksum(meta['registry'])};
        vm.etch(at, address(new PreregisteredCriteria()).code);
        reg = PreregisteredCriteria(at);
    }}

    function test_supportsInterface() public view {{
        assertTrue(reg.supportsInterface(type(IPreregisteredCriteria).interfaceId));
        assertTrue(reg.supportsInterface(0x01ffc9a7));
        assertFalse(reg.supportsInterface(0xffffffff));
    }}

{body}
}}
""")
    print(f"wrote {OUT.relative_to(ROOT)} with {len(cases) + 1} tests")


if __name__ == "__main__":
    main()
