// SPDX-License-Identifier: CC0-1.0
// GENERATED by tools/gen_foundry_tests.py from vectors/onchain — do not edit by hand.
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {PreregisteredCriteria, IPreregisteredCriteria} from "../PreregisteredCriteria.sol";

contract ERC8412VectorsTest is Test {
    PreregisteredCriteria internal reg;
    address internal author = vm.addr(uint256(keccak256("erc8412:author")));
    address internal verifier = vm.addr(uint256(keccak256("erc8412:verifier")));
    address internal stranger = vm.addr(uint256(keccak256("erc8412:stranger")));
    address internal author2 = vm.addr(uint256(keccak256("erc8412:author2")));

    function setUp() public {
        vm.chainId(31337);
        address at = 0x8412000000000000000000000000000000008412;
        vm.etch(at, address(new PreregisteredCriteria()).code);
        reg = PreregisteredCriteria(at);
    }

    function test_supportsInterface() public view {
        assertTrue(reg.supportsInterface(type(IPreregisteredCriteria).interfaceId));
        assertTrue(reg.supportsInterface(0x01ffc9a7));
        assertFalse(reg.supportsInterface(0xffffffff));
    }

    /// DUP (MUST): Same author, criteriaDigest and taskRef twice reverts.
    function test_DUP_duplicate_preregistration() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1100);
        vm.prank(author);
        vm.expectRevert(); // DUP
        reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
    }

    /// E1 (MUST): expiry == block.timestamp is rejected.
    function test_E1_expiry_equals_now() public {
        vm.warp(1000);
        vm.prank(author);
        vm.expectRevert(); // E1
        reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 1000, verifier, bytes32(0));
    }

    /// E1 (MUST): expiry < block.timestamp is rejected.
    function test_E1_expiry_in_past() public {
        vm.warp(1000);
        vm.prank(author);
        vm.expectRevert(); // E1
        reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 999, verifier, bytes32(0));
    }

    /// E10 (MUST): A recorded verdict is final; a second attestation reverts.
    function test_E10_second_attestation() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1200);
        vm.prank(verifier);
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.NotSatisfied, hex"14");
        vm.warp(1300);
        vm.prank(verifier);
        vm.expectRevert(); // E10
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"60");
        {
            (,,, IPreregisteredCriteria.Verdict v,,) = reg.getAttestation(p1);
            assertEq(uint8(v), uint8(IPreregisteredCriteria.Verdict.NotSatisfied));
        }
    }

    /// E10 (MUST): ExpiredUnresolved is terminal (also past expiry, so E7 applies too).
    function test_E10_attest_after_expired_unresolved() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(2001);
        vm.prank(stranger);
        reg.resolveExpired(p1);
        vm.warp(2001);
        vm.prank(verifier);
        vm.expectRevert(); // E10
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"60");
        {
            (,,, IPreregisteredCriteria.Verdict v,,) = reg.getAttestation(p1);
            assertEq(uint8(v), uint8(IPreregisteredCriteria.Verdict.ExpiredUnresolved));
        }
    }

    /// E11 (MUST): NotSatisfied with no UNMET obligation is rejected.
    function test_E11_not_satisfied_all_met() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        vm.expectRevert(); // E11
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.NotSatisfied, hex"54");
    }

    /// E11 (MUST): Indeterminate needs at least one undecided (UNMET) obligation.
    function test_E11_indeterminate_nothing_unmet() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        vm.expectRevert(); // E11
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Indeterminate, hex"6c");
    }

    /// E12 (MUST): Superseding an unknown preregistrationId reverts.
    function test_E12_supersede_unknown_prior() public {
        vm.warp(1000);
        vm.prank(author);
        vm.expectRevert(); // E12
        reg.preregister(bytes32(0x9f94dd8c7be75d866c8dce502d6d3fdcebd78a20ab090209619020edb1a891c1), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0x7888beda87451d1856f6fd577c0b8da40f7cff6d24f3983f06086e56332c147f));
    }

    /// E12 (MUST): Only the same author may supersede.
    function test_E12_supersede_by_other_author() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1100);
        vm.prank(author2);
        vm.expectRevert(); // E12
        reg.preregister(bytes32(0x9f94dd8c7be75d866c8dce502d6d3fdcebd78a20ab090209619020edb1a891c1), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, p1);
    }

    /// E12 (MUST): The superseding preregistration must share taskRef.
    function test_E12_supersede_other_task() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1100);
        vm.prank(author);
        vm.expectRevert(); // E12
        reg.preregister(bytes32(0x9f94dd8c7be75d866c8dce502d6d3fdcebd78a20ab090209619020edb1a891c1), bytes32(0x36dc41127e2a8440bc08763f20a1d312ed807ead087add9b286bbb0ef719cea6), 3, hex"70", 2000, verifier, p1);
    }

    /// E12 (MUST): A preregistration can be superseded only once.
    function test_E12_supersede_twice() public {
        bytes32 p1;
        bytes32 p2;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1100);
        vm.prank(author);
        p2 = reg.preregister(bytes32(0x9f94dd8c7be75d866c8dce502d6d3fdcebd78a20ab090209619020edb1a891c1), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, p1);
        vm.warp(1200);
        vm.prank(author);
        vm.expectRevert(); // E12
        reg.preregister(bytes32(0xecc3e0d55e02eb23a42704f7f086fc4c0d4cc548cce7a2487cf4fb1663472d10), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, p1);
    }

    /// E12 (MUST): A Satisfied verdict cannot be superseded.
    function test_E12_supersede_after_satisfied() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1200);
        vm.prank(verifier);
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"60");
        vm.warp(1300);
        vm.prank(author);
        vm.expectRevert(); // E12
        reg.preregister(bytes32(0x9f94dd8c7be75d866c8dce502d6d3fdcebd78a20ab090209619020edb1a891c1), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, p1);
    }

    /// E12 (MUST): A NotSatisfied verdict cannot be superseded.
    function test_E12_supersede_after_not_satisfied() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1200);
        vm.prank(verifier);
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.NotSatisfied, hex"14");
        vm.warp(1300);
        vm.prank(author);
        vm.expectRevert(); // E12
        reg.preregister(bytes32(0x9f94dd8c7be75d866c8dce502d6d3fdcebd78a20ab090209619020edb1a891c1), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, p1);
    }

    /// E12 (MUST): ExpiredUnresolved cannot be superseded.
    function test_E12_supersede_after_expired() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(2001);
        vm.prank(stranger);
        reg.resolveExpired(p1);
        vm.warp(2002);
        vm.prank(author);
        vm.expectRevert(); // E12
        reg.preregister(bytes32(0x9f94dd8c7be75d866c8dce502d6d3fdcebd78a20ab090209619020edb1a891c1), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 9000, verifier, p1);
    }

    /// E13 (MUST): A superseded preregistration cannot be attested.
    function test_E13_attest_superseded() public {
        bytes32 p1;
        bytes32 p2;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1100);
        vm.prank(author);
        p2 = reg.preregister(bytes32(0x9f94dd8c7be75d866c8dce502d6d3fdcebd78a20ab090209619020edb1a891c1), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, p1);
        vm.warp(1200);
        vm.prank(verifier);
        vm.expectRevert(); // E13
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"60");
    }

    /// E14 (MUST): verifier == address(0) is rejected.
    function test_E14_zero_verifier() public {
        vm.warp(1000);
        vm.prank(author);
        vm.expectRevert(); // E14
        reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, address(0), bytes32(0));
    }

    /// E14 (SHOULD): verifier == msg.sender SHOULD be rejected.
    function test_E14_author_is_verifier() public {
        vm.warp(1000);
        vm.prank(author);
        vm.expectRevert(); // E14
        reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, author, bytes32(0));
    }

    /// E2 (MUST): 3 obligations need exactly 1 flag byte.
    function test_E2_flags_wrong_length() public {
        vm.warp(1000);
        vm.prank(author);
        vm.expectRevert(); // E2
        reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"7000", 2000, verifier, bytes32(0));
    }

    /// E2 (MUST): Trailing pad bits of obligationFlags must be zero.
    function test_E2_flags_nonzero_pad() public {
        vm.warp(1000);
        vm.prank(author);
        vm.expectRevert(); // E2
        reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"71", 2000, verifier, bytes32(0));
    }

    /// E2 (MUST): obligationOutcomes length must match obligationCount.
    function test_E2_outcomes_wrong_length() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        vm.expectRevert(); // E2
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"6400");
    }

    /// E2 (MUST): Trailing pad bits of obligationOutcomes must be zero.
    function test_E2_outcomes_nonzero_pad() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        vm.expectRevert(); // E2
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"63");
    }

    /// E3 (MUST): Only the recorded verifier may attest (front-running guard).
    function test_E3_attest_by_stranger() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(stranger);
        vm.expectRevert(); // E3
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"60");
    }

    /// E3 (MUST): The criteria author is not the verifier and cannot attest.
    function test_E3_attest_by_author() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(author);
        vm.expectRevert(); // E3
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"60");
    }

    /// E4 (MUST): Satisfied over a required UNMET is unrepresentable.
    function test_E4_satisfied_with_required_unmet() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        vm.expectRevert(); // E4
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"14");
    }

    /// E5 (MUST): WAIVED on a non-waivable obligation is rejected.
    function test_E5_waived_not_waivable() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        vm.expectRevert(); // E5
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"94");
    }

    /// E6 (MUST): NOT_APPLICABLE on a required obligation is rejected.
    function test_E6_not_applicable_on_required() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        vm.expectRevert(); // E6
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.NotSatisfied, hex"d0");
    }

    /// E7 (MUST): Attestation at expiry + 1 reverts.
    function test_E7_attest_after_expiry() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(2001);
        vm.prank(verifier);
        vm.expectRevert(); // E7
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"60");
    }

    /// E8 (MUST): Resolution at exactly expiry reverts (windows are disjoint).
    function test_E8_resolve_at_expiry() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(2000);
        vm.prank(stranger);
        vm.expectRevert(); // E8
        reg.resolveExpired(p1);
    }

    /// E8 (MUST): Resolution before expiry reverts.
    function test_E8_resolve_before_expiry() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(stranger);
        vm.expectRevert(); // E8
        reg.resolveExpired(p1);
    }

    /// E8 (MUST): Resolution after an attestation reverts.
    function test_E8_resolve_after_attestation() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"60");
        vm.warp(2001);
        vm.prank(stranger);
        vm.expectRevert(); // E8
        reg.resolveExpired(p1);
        {
            (,,, IPreregisteredCriteria.Verdict v,,) = reg.getAttestation(p1);
            assertEq(uint8(v), uint8(IPreregisteredCriteria.Verdict.Satisfied));
        }
    }

    /// E8 (MUST): A superseded preregistration cannot be resolved.
    function test_E8_resolve_superseded() public {
        bytes32 p1;
        bytes32 p2;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1100);
        vm.prank(author);
        p2 = reg.preregister(bytes32(0x9f94dd8c7be75d866c8dce502d6d3fdcebd78a20ab090209619020edb1a891c1), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 5000, verifier, p1);
        vm.warp(2001);
        vm.prank(stranger);
        vm.expectRevert(); // E8
        reg.resolveExpired(p1);
    }

    /// E8 (MUST): The reported gap: at expiry, resolution fails and attestation succeeds; nothing overwrites.
    function test_E8_boundary_no_overwrite() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(2000);
        vm.prank(stranger);
        vm.expectRevert(); // E8
        reg.resolveExpired(p1);
        vm.warp(2000);
        vm.prank(verifier);
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"60");
        {
            (,,, IPreregisteredCriteria.Verdict v,,) = reg.getAttestation(p1);
            assertEq(uint8(v), uint8(IPreregisteredCriteria.Verdict.Satisfied));
        }
    }

    /// E9 (MUST): verdict == None is rejected.
    function test_E9_verdict_none() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        vm.expectRevert(); // E9
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.None, hex"60");
    }

    /// E9 (MUST): Verifiers cannot attest ExpiredUnresolved directly.
    function test_E9_verdict_expired_unresolved() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        vm.expectRevert(); // E9
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.ExpiredUnresolved, hex"60");
    }

    /// ID (MUST): preregistrationId == keccak256(abi.encode(chainid, registry, author, criteriaDigest, taskRef)).
    function test_ID_preregistration_id_formula() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        assertEq(p1, bytes32(0x512b2bd580b8311e1f340ce0c00930db143cc56209adfab13236d7dfa9982941));
        assertEq(p1, keccak256(abi.encode(block.chainid, address(reg), author, bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f))));
    }

    /// OK (MUST): Required MET, waivable WAIVED, optional UNMET -> Satisfied.
    function test_OK_lifecycle_satisfied() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"60");
        {
            (,,, IPreregisteredCriteria.Verdict v,,) = reg.getAttestation(p1);
            assertEq(uint8(v), uint8(IPreregisteredCriteria.Verdict.Satisfied));
        }
    }

    /// OK (MUST): A required obligation UNMET -> NotSatisfied.
    function test_OK_lifecycle_not_satisfied() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.NotSatisfied, hex"14");
        {
            (,,, IPreregisteredCriteria.Verdict v,,) = reg.getAttestation(p1);
            assertEq(uint8(v), uint8(IPreregisteredCriteria.Verdict.NotSatisfied));
        }
    }

    /// OK (MUST): Undecided required obligation encoded UNMET -> Indeterminate.
    function test_OK_lifecycle_indeterminate() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Indeterminate, hex"14");
        {
            (,,, IPreregisteredCriteria.Verdict v,,) = reg.getAttestation(p1);
            assertEq(uint8(v), uint8(IPreregisteredCriteria.Verdict.Indeterminate));
        }
    }

    /// OK (MUST): NOT_APPLICABLE is allowed on an optional obligation.
    function test_OK_optional_not_applicable() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1500);
        vm.prank(verifier);
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"5c");
    }

    /// OK (MUST): E7 boundary: attestation at block.timestamp == expiry succeeds.
    function test_OK_attest_exactly_at_expiry() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(2000);
        vm.prank(verifier);
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"60");
    }

    /// OK (MUST): E8: any caller may resolve at expiry + 1; verdict becomes ExpiredUnresolved.
    function test_OK_resolve_after_expiry_permissionless() public {
        bytes32 p1;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(2001);
        vm.prank(stranger);
        reg.resolveExpired(p1);
        {
            (,,, IPreregisteredCriteria.Verdict v,,) = reg.getAttestation(p1);
            assertEq(uint8(v), uint8(IPreregisteredCriteria.Verdict.ExpiredUnresolved));
        }
    }

    /// OK (MUST): Re-registration before any verdict; new one is attestable.
    function test_OK_supersede_before_attestation() public {
        bytes32 p1;
        bytes32 p2;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1100);
        vm.prank(author);
        p2 = reg.preregister(bytes32(0x9f94dd8c7be75d866c8dce502d6d3fdcebd78a20ab090209619020edb1a891c1), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, p1);
        vm.warp(1200);
        vm.prank(verifier);
        reg.attestOutcome(p2, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"60");
    }

    /// OK (MUST): E12 permits superseding an Indeterminate verdict.
    function test_OK_supersede_after_indeterminate() public {
        bytes32 p1;
        bytes32 p2;
        vm.warp(1000);
        vm.prank(author);
        p1 = reg.preregister(bytes32(0x731e64bc4d93f1e75ce274b180889ca06f8d6192022df8f63825fdb6f0438b29), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, bytes32(0));
        vm.warp(1200);
        vm.prank(verifier);
        reg.attestOutcome(p1, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Indeterminate, hex"14");
        vm.warp(1300);
        vm.prank(author);
        p2 = reg.preregister(bytes32(0x9f94dd8c7be75d866c8dce502d6d3fdcebd78a20ab090209619020edb1a891c1), bytes32(0xa48d4955fc8d2b9b4db01452af27d26bd30ca536fabafe34b0aeac4d32942f4f), 3, hex"70", 2000, verifier, p1);
        vm.warp(1400);
        vm.prank(verifier);
        reg.attestOutcome(p2, bytes32(0xa756cae0ef6a0b6531305b24d364448a4b2637b6bd5b8b1f918ce1cfaa11271c), bytes32(0xa2e73eb835e4b74aaee074442d0fc621373da297cecf0a7468eed5353d7f784b), IPreregisteredCriteria.Verdict.Satisfied, hex"60");
    }
}
