// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

/// @title IUltraVerifier -- Interface for Barretenberg-generated UltraHonk verifiers
/// @notice Each Noir circuit produces a verifier contract implementing this interface
/// @dev Generated by `bb write_solidity_verifier` from a compiled Noir circuit's verification key
interface IUltraVerifier {
    /// @notice Verify an UltraHonk proof
    /// @param proof The raw proof bytes
    /// @param publicInputs The public inputs as bytes32 array (order matches Noir circuit)
    /// @return valid Whether the proof verifies against the embedded verification key
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool valid);
}
