//SPDX-License-Identifier: Unlicensed
pragma solidity ^0.8.27;

string constant PROVIDED_NODE_REFERENCE_IS_NIL_ERR = "A-004";
string constant NODE_INDEX_NOT_EXISTS_ERR = "A-005";
string constant AUTH_ADMIN_ERR = "A-006";
string constant NODE_NOT_EXISTS_ERR = "A-008";
string constant SUPPLIED_NODE_ID_IS_NIL_ERR = "A-009";
string constant SUPPLIED_NODE_ID_NOT_UNIQUE_ERR = "A-010";
string constant SUPPLIED_VARIABLES_LIST_LENGTH_NOT_MATCHES_EXPECTED_LENGTH_ERR = "A-013";

string constant DUPLICATED_ROOT_NODE_ERR = "T-001";
string constant MISSING_ROOT_NODE_ERR = "T-002";
string constant INIT_NODES_LIST_IS_LARGER_THAN_MAX_LENGTH_ERR = "T-003";
string constant GRAPH_ALREADY_INITIALIZED_ERR = "T-004";
string constant GRAPH_NOT_INITIALIZED_ERR = "T-005";

string constant NODE_VARIABLES_LIST_LENGTH_VIOLATES_DESCRIPTOR_ERR = "U-001";

string constant INCORRECT_NODE_ARGUMENTS_NUMBER_IS_SUPPLIED_ERR = "V-001";
string constant ARTIFACT_INSTANCE_NOT_SUPPORTS_REQUIRED_INTERFACE_ERR = "A-002";
string constant ARTIFACT_INSTANCE_NOT_IMPLEMENTS_ERC165_INTERFACE_ERR = "A-003";
