on:
  pull_request_target:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Jekyll Label Bot
jobs:
  jekyll-label-action:
    name: Label
    runs-on: ubuntu-latest
    
    steps:
      - uses: Pandapip1/jekyll-label-action@753297a43dc77d48a8b92e5d66622c452a5247a9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: config/.jekyll-labels.yml
